C:\Python27\python.exe ex01_analysis_setup.py
C:\Python27\python.exe ex02_meas_geometry.py
C:\Python27\python.exe ex03_plume_background.py
C:\Python27\python.exe ex04_prep_aa_imglist.py
C:\Python27\python.exe ex05_cell_calib_auto.py
C:\Python27\python.exe ex06_doas_calib.py
C:\Python27\python.exe ex07_doas_cell_calib.py
C:\Python27\python.exe ex08_velo_crosscorr.py
C:\Python27\python.exe ex09_velo_optflow.py
C:\Python27\python.exe ex10_bg_imglists.py
C:\Python27\python.exe ex11_signal_dilution.py
C:\Python27\python.exe ex12_emission_rate.py